### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jmarcelino** [simonqbs/cayennelpp-python#1]
Hi Simon,

Thank you so much for creating this code, I tried it for the TTN workshops and it worked great with the Pysense and Cayennne. 

Would you mind if we (Pycom) share it with the community? You can email me at jmarcelino@pycom.io if you prefer.

Thank you.

**Comment by simonqbs** [comment]
Glad you found it useful :)  I've addded a license (not really sure why I didn't do it before, but got better things to do than dealing with legal stuff ;)) so you can use it as you please.

**Comment by jmarcelino** [comment]
Thanks a lot!
